package com.payload.parser.sdlc;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class SdlcGeneratorService {

    static final int MAX_FOLDERS = 1500;
    static final int MAX_TREE_LINES = 80;
    static final int MAX_TREE_DEPTH = 3;
    static final int MAX_EDITS = 60;
    static final int MAX_EDIT_CHARS = 64 * 1024;

    private static final Set<String> IGNORED_FOLDERS = Set.of(
            ".git", "node_modules", "target", "build", "dist", "out", "bin", "obj", ".gradle", ".idea", ".vscode",
            "venv", ".venv", "__pycache__", ".pytest_cache", "coverage", ".next", ".nuxt", "vendor", ".terraform");
    private static final Pattern PREFIX = Pattern.compile("^[a-z][a-z0-9]{0,11}-$");
    private static final Pattern SKILL_PATH = Pattern.compile("^\\.claude/skills/([^/]+)/(.+)$");

    private final SdlcTemplateStore store;
    private final ObjectMapper mapper;

    public SdlcGeneratorService(SdlcTemplateStore store, ObjectMapper mapper) {
        this.store = store;
        this.mapper = mapper.copy().enable(SerializationFeature.INDENT_OUTPUT);
    }

    public SdlcKit generate(SdlcRequest request) {
        return generate(request, SdlcEdition.PROJECT);
    }

    public SdlcKit generate(SdlcRequest request, boolean plugin) {
        return generate(request, plugin ? SdlcEdition.PLUGIN : SdlcEdition.PROJECT);
    }

    /**
     * Builds the kit. The project edition is unzipped into a project; the workspace edition into a folder that
     * holds several services, each with its own repository; the plugin edition is a Claude Code plugin whose
     * project files sit in {@code templates/} and are copied into each project by its setup command.
     */
    public SdlcKit generate(SdlcRequest request, SdlcEdition edition) {
        boolean plugin = edition == SdlcEdition.PLUGIN;
        boolean workspace = edition == SdlcEdition.WORKSPACE;
        List<String> packIds = selectPacks(request);
        if (plugin) packIds.add("plugin");
        if (workspace) packIds.add("workspace");
        Set<String> flags = new HashSet<>(packIds);
        Map<String, String> values = values(request);
        List<SdlcRequest.Service> services = workspace ? normaliseServices(request.servicesOrEmpty()) : List.of();
        if (workspace) values.putAll(serviceValues(services));
        values.forEach((k, v) -> { if (!v.isBlank()) flags.add(k); });
        if (request.existingClaudeMd() && !plugin) flags.add("existingClaudeMd");

        Map<String, String> files = new TreeMap<>();
        for (String id : packIds) {
            for (Map.Entry<String, String> f : store.pack(id).files().entrySet()) {
                if (files.put(f.getKey(), SdlcRenderer.render(f.getValue(), flags, values)) != null) {
                    throw new IllegalStateException("Template " + f.getKey() + " exists in two packs");
                }
            }
        }

        if (workspace) {
            addServiceDocs(files, services, flags, values);
            files.replaceAll((path, text) -> path.startsWith(".claude/rules/") ? anywherePaths(text) : text);
        }

        if (!plugin) files = applyPrefix(files, request.commandPrefix());
        addLintHook(files, request.lintCommand(), request.hookShell());

        String claudeFile = "CLAUDE.md";
        if (request.existingClaudeMd() && !plugin) {
            files.put("CLAUDE.sdlc.md", files.remove("CLAUDE.md"));
            claudeFile = "CLAUDE.sdlc.md";
        }

        String header = "<!-- Generated by jsonxmleditor.com · Claude Code SDLC Kit " + store.kitVersion()
                + " · " + LocalDate.now() + " -->";
        files.replaceAll((path, text) -> addHeader(path, text, header));

        List<SdlcIssue> issues = new ArrayList<>();
        if (plugin) {
            issues.addAll(SdlcValidator.validate(files, Set.of(), claudeFile));
            files = SdlcPluginLayout.convert(files, store.kitVersion(), mapper);
            Set<String> edited = applyEdits(files, request.editsOrEmpty(), issues);
            issues.addAll(SdlcPluginLayout.validate(files, edited));
        } else {
            Set<String> edited = applyEdits(files, request.editsOrEmpty(), issues);
            issues.addAll(0, SdlcValidator.validate(files, edited, claudeFile));
        }

        Map<String, String> ordered = new LinkedHashMap<>();
        files.entrySet().stream()
                .sorted(Comparator.comparing((Map.Entry<String, String> e) -> rank(e.getKey())).thenComparing(Map.Entry::getKey))
                .forEach(e -> ordered.put(e.getKey(), e.getValue()));
        return new SdlcKit(ordered, issues);
    }

    static final int MAX_SERVICES = 60;
    private static final Pattern SERVICE_FOLDER = Pattern.compile("^[A-Za-z0-9._-]{1,80}$");
    private static final Pattern GIT_URL = Pattern.compile("^(https?://|ssh://|git@)[^\\s`|<>]{3,290}$");
    private static final String SERVICE_TEMPLATE = "docs/sdlc/services/_template-service.md";

    static List<SdlcRequest.Service> normaliseServices(List<SdlcRequest.Service> raw) {
        if (raw.size() > MAX_SERVICES) throw new SdlcRequestException("Too many services (maximum " + MAX_SERVICES + ").");
        Map<String, SdlcRequest.Service> out = new TreeMap<>();
        for (SdlcRequest.Service s : raw) {
            if (s == null || s.folder() == null) continue;
            String folder = s.folder().strip().replace('\\', '/').replaceAll("^\\./|/+$", "");
            if (folder.isEmpty()) continue;
            if (!SERVICE_FOLDER.matcher(folder).matches() || folder.startsWith(".") || IGNORED_FOLDERS.contains(folder)) {
                throw new SdlcRequestException("\"" + folder + "\" isn't a valid service folder name (one folder, letters, digits, dot, dash, underscore).");
            }
            String repo = s.repo() == null ? "" : s.repo().strip();
            if (!repo.isEmpty() && !GIT_URL.matcher(repo).matches()) {
                throw new SdlcRequestException("The git URL for " + folder + " doesn't look like a git URL.");
            }
            out.putIfAbsent(folder, new SdlcRequest.Service(folder,
                    clean(s.purpose(), 200, false).replace("|", "\\|"),
                    clean(s.stack(), 200, false).replace("|", "\\|"), repo));
        }
        return new ArrayList<>(out.values());
    }

    static Map<String, String> serviceValues(List<SdlcRequest.Service> services) {
        StringBuilder table = new StringBuilder(), txt = new StringBuilder(), ignores = new StringBuilder();
        for (SdlcRequest.Service s : services) {
            if (table.length() > 0) { table.append('\n'); txt.append('\n'); ignores.append('\n'); }
            table.append("| `").append(s.folder()).append("/` | ").append(s.purpose()).append(" | ").append(s.stack())
                    .append(" | ").append(s.repo()).append(" |");
            txt.append(s.repo().isEmpty() ? "# " + s.folder() + " <add the git URL>" : s.folder() + " " + s.repo());
            ignores.append('/').append(s.folder()).append('/');
        }
        Map<String, String> v = new HashMap<>();
        v.put("servicesTable", table.toString());
        v.put("servicesTxt", txt.toString());
        v.put("serviceIgnores", ignores.toString());
        return v;
    }

    private void addServiceDocs(Map<String, String> files, List<SdlcRequest.Service> services, Set<String> flags,
                                Map<String, String> values) {
        String template = store.pack("workspace").files().get(SERVICE_TEMPLATE);
        for (SdlcRequest.Service s : services) {
            Map<String, String> v = new HashMap<>(values);
            v.put("serviceFolder", s.folder());
            v.put("servicePurpose", s.purpose());
            v.put("serviceStack", s.stack());
            v.put("serviceRepo", s.repo());
            Set<String> f = new HashSet<>(flags);
            for (String key : List.of("serviceFolder", "servicePurpose", "serviceStack", "serviceRepo")) {
                if (!v.get(key).isBlank()) f.add(key);
            }
            files.put("docs/sdlc/services/" + s.folder() + ".md", SdlcRenderer.render(template, f, v));
        }
    }

    /** In a workspace, code sits one level down (service/src/…), so rule globs must match at any depth. */
    static String anywherePaths(String text) {
        if (!text.startsWith("---\n")) return text;
        int end = text.indexOf("\n---", 4);
        if (end < 0) return text;
        String header = text.substring(0, end).replaceAll("(?m)^(\\s*- \")(?!\\*\\*/|/)([^\"]+\")", "$1**/$2");
        return header + text.substring(end);
    }

    List<String> selectPacks(SdlcRequest r) {
        List<String> ids = new ArrayList<>();
        ids.add("core");
        if (r.developer()) ids.add("dev");
        if (r.tester()) ids.add("tester");
        addGroup(ids, r.profilesOrEmpty(), "profile", 10);
        addGroup(ids, r.testFrameworksOrEmpty(), "framework", 30);
        addGroup(ids, r.extrasOrEmpty(), "extra", 20);
        for (String id : ids) {
            String requires = store.pack(id).requires();
            if (requires != null && !ids.contains(requires)) {
                throw new SdlcRequestException(store.pack(id).label() + " needs the "
                        + store.pack(requires).label() + " role.");
            }
        }
        return ids;
    }

    private void addGroup(List<String> ids, List<String> requested, String group, int max) {
        if (requested.size() > max) throw new SdlcRequestException("Too many " + group + "s selected.");
        for (String id : new LinkedHashSet<>(requested)) {
            SdlcPack pack = store.pack(id);
            if (pack == null || !pack.group().equals(group)) throw new SdlcRequestException("Unknown " + group + ": " + id);
            ids.add(id);
        }
    }

    Map<String, String> values(SdlcRequest r) {
        Map<String, String> v = new HashMap<>();
        v.put("projectName", clean(r.projectName(), 80, false));
        v.put("projectDescription", clean(r.projectDescription(), 600, true));
        v.put("projectStack", clean(r.projectStack(), 200, false));
        List<String> labels = r.testFrameworksOrEmpty().stream()
                .map(store::pack).filter(p -> p != null).map(SdlcPack::label).toList();
        v.put("testFrameworks", String.join(", ", labels));
        List<SdlcRequest.FolderNote> folders = normaliseFolders(r.foldersOrEmpty());
        v.put("folderTree", folderTree(folders));
        v.put("folderTable", folderTable(folders));
        return v;
    }

    static String clean(String s, int max, boolean multiline) {
        if (s == null) return "";
        String t = s.replace("\r\n", "\n").replace('\r', '\n').replace("{{", "{ {").replace("}}", "} }");
        t = t.replaceAll("<!--|-->", "");
        if (!multiline) t = t.replace('\n', ' ');
        t = t.strip();
        if (t.length() > max) throw new SdlcRequestException("Text is too long (" + t.length() + " characters; maximum " + max + ").");
        return t;
    }

    static List<SdlcRequest.FolderNote> normaliseFolders(List<SdlcRequest.FolderNote> raw) {
        if (raw.size() > MAX_FOLDERS) throw new SdlcRequestException("Too many folders (maximum " + MAX_FOLDERS + ").");
        Map<String, String> out = new TreeMap<>();
        for (SdlcRequest.FolderNote f : raw) {
            if (f == null || f.path() == null) continue;
            String p = f.path().strip().replace('\\', '/').replaceAll("/+", "/");
            while (p.startsWith("./") || p.startsWith("/")) p = p.substring(p.startsWith("./") ? 2 : 1);
            while (p.endsWith("/")) p = p.substring(0, p.length() - 1);
            if (p.isEmpty() || p.length() > 200 || p.contains("{{") || p.contains("`") || p.contains("|")) continue;
            String[] parts = p.split("/");
            boolean skip = false;
            for (String part : parts) {
                if (part.equals("..") || part.equals(".") || IGNORED_FOLDERS.contains(part)) { skip = true; break; }
            }
            if (skip) continue;
            String note = f.note() == null ? "" : clean(f.note(), 200, false).replace("|", "\\|");
            out.merge(p, note, (a, b) -> a.isEmpty() ? b : a);
        }
        List<SdlcRequest.FolderNote> list = new ArrayList<>();
        out.forEach((p, n) -> list.add(new SdlcRequest.FolderNote(p, n)));
        return list;
    }

    static String folderTree(List<SdlcRequest.FolderNote> folders) {
        if (folders.isEmpty()) return "";
        Node root = new Node();
        for (SdlcRequest.FolderNote f : folders) {
            Node n = root;
            String[] parts = f.path().split("/");
            for (int i = 0; i < parts.length && i < MAX_TREE_DEPTH; i++) n = n.children.computeIfAbsent(parts[i], k -> new Node());
        }
        List<String> lines = new ArrayList<>();
        int[] omitted = {0};
        walk(root, "", lines, omitted);
        if (omitted[0] > 0) lines.add("… " + omitted[0] + " more folders not shown");
        return String.join("\n", lines);
    }

    private static final class Node {
        final Map<String, Node> children = new TreeMap<>();
    }

    private static void walk(Node node, String indent, List<String> lines, int[] omitted) {
        int i = 0;
        for (Map.Entry<String, Node> e : node.children.entrySet()) {
            boolean last = ++i == node.children.size();
            if (lines.size() >= MAX_TREE_LINES) { omitted[0] += 1 + count(e.getValue()); continue; }
            lines.add(indent + (last ? "└── " : "├── ") + e.getKey() + "/");
            walk(e.getValue(), indent + (last ? "    " : "│   "), lines, omitted);
        }
    }

    private static int count(Node n) {
        int c = 0;
        for (Node child : n.children.values()) c += 1 + count(child);
        return c;
    }

    static String folderTable(List<SdlcRequest.FolderNote> folders) {
        StringBuilder sb = new StringBuilder();
        for (SdlcRequest.FolderNote f : folders) {
            if (f.note().isBlank()) continue;
            if (sb.length() > 0) sb.append('\n');
            sb.append("| `").append(f.path()).append("/` | ").append(f.note()).append(" |");
        }
        return sb.toString();
    }

    Map<String, String> applyPrefix(Map<String, String> files, String prefix) {
        if (prefix == null || prefix.isBlank()) return files;
        String p = prefix.strip().toLowerCase();
        if (!p.endsWith("-")) p = p + "-";
        if (!PREFIX.matcher(p).matches()) {
            throw new SdlcRequestException("The command prefix may use letters and digits only, e.g. \"team\" or \"qa\".");
        }
        Map<String, String> rename = new TreeMap<>(Comparator.comparing(String::length).reversed().thenComparing(s -> s));
        for (String path : files.keySet()) {
            Matcher m = SKILL_PATH.matcher(path);
            if (m.matches() && !m.group(1).startsWith(p)) rename.put(m.group(1), p + m.group(1));
        }
        Map<String, String> out = new TreeMap<>();
        for (Map.Entry<String, String> e : files.entrySet()) {
            String path = e.getKey();
            String text = e.getValue();
            for (Map.Entry<String, String> r : rename.entrySet()) {
                String from = Pattern.quote(r.getKey());
                text = text.replaceAll("\\.claude/skills/" + from + "/", Matcher.quoteReplacement(".claude/skills/" + r.getValue() + "/"))
                        .replaceAll("(?<![\\w/.:-])/" + from + "(?![\\w-])", Matcher.quoteReplacement("/" + r.getValue()));
            }
            Matcher m = SKILL_PATH.matcher(path);
            if (m.matches() && rename.containsKey(m.group(1))) {
                String newName = rename.get(m.group(1));
                path = ".claude/skills/" + newName + "/" + m.group(2);
                if (m.group(2).equals("SKILL.md")) {
                    text = text.replaceFirst("(?m)^name: " + Pattern.quote(m.group(1)) + "$", Matcher.quoteReplacement("name: " + newName));
                }
            }
            out.put(path, text);
        }
        return out;
    }

    void addLintHook(Map<String, String> files, String command, String shell) {
        if (command == null || command.isBlank()) return;
        String cmd = command.strip();
        if (cmd.length() > 300 || cmd.contains("\n") || cmd.contains("\r")) {
            throw new SdlcRequestException("The format/lint command must be a single line of at most 300 characters.");
        }
        if (shell != null && !shell.isBlank() && !shell.equals("bash") && !shell.equals("powershell")) {
            throw new SdlcRequestException("The hook shell must be bash or powershell.");
        }
        try {
            ObjectNode settings = (ObjectNode) mapper.readTree(files.get(".claude/settings.json"));
            ObjectNode hook = mapper.createObjectNode().put("type", "command").put("command", cmd);
            if ("powershell".equals(shell)) hook.put("shell", "powershell");
            ObjectNode group = mapper.createObjectNode();
            group.putArray("hooks").add(hook);
            ObjectNode hooks = settings.get("hooks") instanceof ObjectNode existing ? existing : settings.putObject("hooks");
            ArrayNode stop = hooks.get("Stop") instanceof ArrayNode arr ? arr : hooks.putArray("Stop");
            stop.add(group);
            files.put(".claude/settings.json", mapper.writeValueAsString(settings) + "\n");
        } catch (Exception e) {
            throw new IllegalStateException("Could not add the lint hook to settings.json", e);
        }
    }

    static String addHeader(String path, String text, String header) {
        if (!path.endsWith(".md")) return text;
        if (text.startsWith("---\n")) {
            int end = text.indexOf("\n---\n", 4);
            if (end >= 0) return text.substring(0, end + 5) + header + "\n" + text.substring(end + 5);
        }
        return header + "\n" + text;
    }

    Set<String> applyEdits(Map<String, String> files, Map<String, String> edits, List<SdlcIssue> issues) {
        if (edits.size() > MAX_EDITS) throw new SdlcRequestException("Too many edited files (maximum " + MAX_EDITS + ").");
        Set<String> edited = new HashSet<>();
        for (Map.Entry<String, String> e : edits.entrySet()) {
            String path = e.getKey();
            String text = e.getValue() == null ? "" : e.getValue().replace("\r\n", "\n");
            if (!files.containsKey(path)) {
                issues.add(SdlcIssue.warning(path, "your edit was skipped because this file isn't in the kit with the current choices"));
                continue;
            }
            if (text.length() > MAX_EDIT_CHARS) throw new SdlcRequestException("The edit to " + path + " is too large.");
            files.put(path, text);
            edited.add(path);
        }
        return edited;
    }

    private static final List<String> ORDER = List.of(".claude-plugin/", ".claude/", "skills/", "agents/", "hooks/", "docs/", "templates/");

    private static int rank(String path) {
        if (!path.contains("/")) return 0;
        for (int i = 0; i < ORDER.size(); i++) if (path.startsWith(ORDER.get(i))) return i + 1;
        return ORDER.size() + 1;
    }
}
