package com.payload.parser.enumration;

public enum Type {
    JSON_TO_XML, XML_TO_JSON, JSON_FORMAT, XML_FORMAT, JSON_TO_TOML, XML_TO_TOML,
    JSON_TO_YAML, XML_TO_YAML, JSON_SORT, XML_SORT, JSON_TO_CSV, XML_TO_CSV,
    CSV_TO_JSON, CSV_TO_XML, JAVA, PROPERTY_TO_YAML, JSON_TO_SQL, XML_TO_SQL, YAML_TO_PROPERTY
}